### ISSUE TITLE
Automatic detection of repository root times out with large containers

### ISSUE THREAD

**Issue by peichman-umd** [fcrepo4-labs/fcrepo-import-export#114]
During the export process, the exporter attempts to automatically determine the repository root by traversing the path hierarchy of the given endpoint URL and checking each resource for the presence of a `<> rdf:type fedora:RepositoryRoot` triple. In cases where there is a container with many children, the request for the container can time out before the response can be generated (in our case at UMD, we have a 10 minute request timeout on our Apache frontend).

Solutions would include:

1. Allowing the user to explicitly specify the repository root, and thus skip the automatic detection process.
2. If automatic detection is still required, request the container representations as N-Triples, so the response begins streaming immediately.

**Comment by peichman-umd** [comment]
Cross-filed as https://jira.duraspace.org/browse/FCREPO-2741

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4-labs/fcrepo-import-export/commit/98d3702e385a2685214b33a1d932d5eaf954a792
